In [1]:
"""
(*) A simple neural network making a prediction (one input, one output)
"""

# A neural network with a single weight mapping from input to output. 
# -- It accepts an input variable as information and a weight variable as knowledge and outputs a prediction.
# -- Another way to think about a neural network’s weight value is as a measure of sensitivity between the input of the network
#    and its prediction. If the weight is very high, then even the tiniest input can create a really large prediction! If the weight
#    is very small, then even large inputs will make small predictions. 
weight = 0.1

def neural_network(input, weight):
    prediction = input * weight
    return prediction

# Input data
number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]

# Use the neural network to make the prediction
pred = neural_network(input, weight)
print('%f' % pred)

0.850000


In [1]:
"""
(*) Neural network can combine intelligence from multiple datapoints (multiple inputs, one output)
"""

# Performing a weighted sum of inputs
def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0.0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

# This new neural network can accept multiple inputs at a time per prediction. This allows the network to combine various forms
# of information to make better-informed decisions. But the fundamental mechanism for using weights hasn’t changed. In other words,
# you multiply each input by its respective weight and then sum all the local predictions together. This is called a weighted sum
# of the input, or a weighted sum for short or dot product.
weights = [0.1, 0.2, 0]

def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred

# Input data (three at a time)
toes =  [8.5,  9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2,  1.3, 0.5, 1.0]
input = [toes[0], wlrec[0], nfans[0]]

# Use the neural network to make the prediction: input is a vector and weights is a vector. 
pred = neural_network(input, weights)
print('%f' % pred)

0.980000


In [ ]:
"""
Important Note:

The intuition behind how and why a dot product (weighted sum) works is easily one of the most important parts of truly understanding
how neural networks make predictions. Loosely stated, a dot product gives you a notion of similarity between two vectors.

What does this mean when a neural network makes a prediction?  Roughly speaking, it means the network gives a high score of the inputs
based on how similar they are to the weights. Both the value of the weight and the value of the input determine the overall impact on the
final score. Finally, a negative weight will cause some inputs to reduce the final prediction (and vice versa).
"""

In [7]:
"""
Numpy version of the above neural network
"""
import numpy as np

weights = np.array([0.1, 0.2, 0])

def neural_network(input, weights):
    pred = input.dot(weights)
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])
input = np.array([toes[0],wlrec[0],nfans[0]])

pred = neural_network(input, weights)
print('%f' % pred)

0.980000


In [9]:
"""
(*) Neural networks can make multiple predictions using only a single input (one input, multiple outputs)
"""

# Performing elementwise multiplication
def ele_mul(number, vector):
    output = [0, 0, 0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

# The most important comment in this setting is to notice that the three predictions are completely separate.
# This network truly behaves as three independent components, each receiving the same input data.
weights = [0.3, 0.2, 0.9]

def neural_network(input, weights):
    pred = ele_mul(input, weights)
    return pred

# Input data
wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]

# Use the neural network to make the prediction
pred = neural_network(input, weights)
print(pred)

[0.195, 0.13, 0.5850000000000001]


In [10]:
"""
(*) Neural networks can make multiple predictions given multiple inputs (multiple inputs, multiple outputs)
"""

# For each output, performing a weighted sum of inputs
def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0, 0, 0]
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
    return output

# You can take two perspectives on this architecture: think of it as either three weights coming out of each input node, or
# three weights going into each output node. For now, I find the latter to be much more beneficial. Think about this neural network
# as three independent dot products: three independent weighted sums of the input. Each output node takes its own weighted sum of
# the input and makes a prediction. 
weights = [[0.1, 0.1, -0.3],
           [0.1, 0.2, 0.0],
           [0.0, 1.3, 0.1]]

def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred

# Input data
toes =  [8.5,  9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2,  1.3, 0.5, 1.0]
input = [toes[0], wlrec[0], nfans[0]]

# Use the neural network to make the prediction
pred = neural_network(input, weights)
print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


In [13]:
"""
(*) Neural networks can be stacked (predicting on predictions)
"""

# You can take the output of one network and feed it as input to another network. This results in two consecutive vector-matrix
# multiplications. It may not yet be clear why you’d predict this way; but some datasets (such as image classification) contain patterns
# that are too complex for a single-weight matrix.

ih_wgt = [[0.1,  0.2, -0.1],
          [-0.1, 0.1,  0.9],
          [0.1,  0.4,  0.1]]
hp_wgt = [[0.3, 1.1, -0.3],
          [0.1, 0.2,  0.0],
          [0.0, 1.3,  0.1]]
weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid  = vect_mat_mul(input, weights[0])
    pred = vect_mat_mul(hid, weights[1])
    return pred

# Input data
toes =  [8.5,  9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2,  1.3, 0.5, 1.0]
input = [toes[0], wlrec[0], nfans[0]]

# predicting on prediction
pred = neural_network(input, weights)
print(pred)

[0.21350000000000002, 0.14500000000000002, 0.5065]


In [14]:
"""
Numpy version of the above neural network
"""

ih_wgt = np.array([[0.1, 0.2, -0.1],
                   [-0.1,0.1, 0.9],
                   [0.1, 0.4, 0.1]]).T

hp_wgt = np.array([[0.3, 1.1, -0.3],
                   [0.1, 0.2, 0.0],
                   [0.0, 1.3, 0.1] ]).T
weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred

toes  = np.array([8.5,  9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2,  1.3, 0.5, 1.0])
input = np.array([toes[0],wlrec[0],nfans[0]])

pred = neural_network(input,weights)
print(pred)

[0.2135 0.145  0.5065]


In [8]:
"""
A Quick Primer on NumPy

When you multiply two variables with the * function, NumPy automatically detects what kinds of variables you’re working with and tries
to figure out the operation you’re talking about. This can be mega-convenient but sometimes makes NumPy code a bit hard to read.
Make sure you keep track of each variable type as you go along.

The general rule of thumb for anything elementwise (+, –, *, /) is that either the two variables must have the same number of columns,
or one of the variables must have only one column.

When you “read NumPy,” you’re really doing two things: reading the operations and keeping track of the shape (number of rows and columns)
of each operation. 
"""
import numpy as np


# Create vectors and matrices
a = np.array([0, 1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
d = np.zeros((2, 4))
e = np.random.rand(2, 5)

print(a)
print(b)
print(c)
print(d)
print(e)

# Operations
print(a * 0.1)       # Scalar-vector multiplication
print(c * 0.2)       # Scalar-matrix multiplication
print(a * b)         # Multiplies elementwise between a and b 
print(a * b * 0.2)  
print(a * c)         # Performs elementwise multiplication on every row of matrix c, because c has the same number of columns as a
#print(a * e)        # Because a and e don’t have the same number of columns, this throws error

# Dot Product
a = np.zeros((1,4))
b = np.zeros((4,3))
c = a.dot(b)

print(c.shape)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.95964005 0.95926755 0.70524519 0.61081255 0.37159998]
 [0.481581   0.86943584 0.10484111 0.4664899  0.85330077]]
[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]
(1, 3)
